In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.decomposition import PCA
import pylab as pl
from sklearn import preprocessing
from sklearn import ensemble
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectFromModel
from sklearn import svm
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF

In [2]:
data1 = pd.read_csv("group1.csv")
df1 = pd.DataFrame(data1) # Converting data to Panda DataFrame
data2 = pd.read_csv("group2.csv")
df2 = pd.DataFrame(data2) # Converting data to Panda DataFrame
data3 = pd.read_csv("group3.csv")
df3 = pd.DataFrame(data3) # Converting data to Panda DataFrame
data4 = pd.read_csv("group4.csv")
df4 = pd.DataFrame(data4) # Converting data to Panda DataFrame
data5 = pd.read_csv("group5.csv")
df5 = pd.DataFrame(data5) # Converting data to Panda DataFrame

## Weight all the features by instruction count rather than a separate instruction

In [3]:
X_1 = df1

Weighted_X1 = X_1[["ilp32",'ilp256','ilp2048','ilp65536','memops','ctrlops','intops','flops','coldref fraction','resuseDist2 fraction','sfp','dfp','noconflict','broadCast','coalesced',
 'shMemBw',
 'gMemBw',
 'blocks',
 'pages',
 'lipRate',
 'mulf',
 'divf',
 'specialFn',
 'lbdiv16',
 'lbdiv32',
 'lbdiv64',
 'lbdiv128',
 'lbdiv256',
 'lbdiv512',
 'lbdiv1024']].multiply(df1["instructionCount"], axis="index")

X_2 = df2

Weighted_X2 = X_2[["ilp32",'ilp256','ilp2048','ilp65536','memops','ctrlops','intops','flops','coldref fraction','resuseDist2 fraction','sfp','dfp','noconflict','broadCast','coalesced',
 'shMemBw',
 'gMemBw',
 'blocks',
 'pages',
 'lipRate',
 'mulf',
 'divf',
 'specialFn',
 'lbdiv16',
 'lbdiv32',
 'lbdiv64',
 'lbdiv128',
 'lbdiv256',
 'lbdiv512',
 'lbdiv1024']].multiply(df2["instructionCount"], axis="index")

X_3 = df3

Weighted_X3 = X_3[["ilp32",'ilp256','ilp2048','ilp65536','memops','ctrlops','intops','flops','coldref fraction','resuseDist2 fraction','sfp','dfp','noconflict','broadCast','coalesced',
 'shMemBw',
 'gMemBw',
 'blocks',
 'pages',
 'lipRate',
 'mulf',
 'divf',
 'specialFn',
 'lbdiv16',
 'lbdiv32',
 'lbdiv64',
 'lbdiv128',
 'lbdiv256',
 'lbdiv512',
 'lbdiv1024']].multiply(df3["instructionCount"], axis="index")

X_4 = df4

Weighted_X4 = X_4[["ilp32",'ilp256','ilp2048','ilp65536','memops','ctrlops','intops','flops','coldref fraction','resuseDist2 fraction','sfp','dfp','noconflict','broadCast','coalesced',
 'shMemBw',
 'gMemBw',
 'blocks',
 'pages',
 'lipRate',
 'mulf',
 'divf',
 'specialFn',
 'lbdiv16',
 'lbdiv32',
 'lbdiv64',
 'lbdiv128',
 'lbdiv256',
 'lbdiv512',
 'lbdiv1024']].multiply(df4["instructionCount"], axis="index")

X_5 = df5

Weighted_X5 = X_5[["ilp32",'ilp256','ilp2048','ilp65536','memops','ctrlops','intops','flops','coldref fraction','resuseDist2 fraction','sfp','dfp','noconflict','broadCast','coalesced',
 'shMemBw',
 'gMemBw',
 'blocks',
 'pages',
 'lipRate',
 'mulf',
 'divf',
 'specialFn',
 'lbdiv16',
 'lbdiv32',
 'lbdiv64',
 'lbdiv128',
 'lbdiv256',
 'lbdiv512',
 'lbdiv1024']].multiply(df5["instructionCount"], axis="index")




In [4]:
Y_train1 = df1['Class']
Y_train2 = df2['Class']
Y_train3 = df3['Class']
Y_train4 = df4['Class']
Y_train5 = df5['Class']

In [5]:
# randomForestT1 = RandomForestClassifier(n_estimators=20,n_jobs=-1,random_state=0)
# randomForestT2 = RandomForestClassifier(n_estimators=20,n_jobs=-1,random_state=0)
# randomForestT3 = RandomForestClassifier(n_estimators=20,n_jobs=-1,random_state=0)
# randomForestT4 = RandomForestClassifier(n_estimators=20,n_jobs=-1,random_state=0)
# randomForestT5 = RandomForestClassifier(n_estimators=20,n_jobs=-1,random_state=0)

# randomForestT1.fit(Weighted_X1,Y_train1)
# randomForestT2.fit(Weighted_X2,Y_train2)
# randomForestT3.fit(Weighted_X3,Y_train3)
# randomForestT4.fit(Weighted_X4,Y_train4)
# randomForestT5.fit(Weighted_X5,Y_train5)

# model1 = SelectFromModel(randomForestT1, prefit=True)
# model2 = SelectFromModel(randomForestT2, prefit=True)
# model3 = SelectFromModel(randomForestT3, prefit=True)
# model4 = SelectFromModel(randomForestT4, prefit=True)
# model5 = SelectFromModel(randomForestT5, prefit=True)
# idxs_selected1 = model1.get_support(indices=True)
# idxs_selected2 = model2.get_support(indices=True)
# idxs_selected3 = model3.get_support(indices=True)
# idxs_selected4 = model4.get_support(indices=True)
# idxs_selected5 = model5.get_support(indices=True)
# X_new1 = model1.transform(Weighted_X1)
# X_new2 = model2.transform(Weighted_X2)
# X_new3 = model3.transform(Weighted_X3)
# X_new4 = model4.transform(Weighted_X4)
# X_new5 = model5.transform(Weighted_X5)

selector1 = SelectKBest(chi2, k=25)
X_new1 =selector1.fit_transform(Weighted_X1, Y_train1)
idxs_selected1 = selector1.get_support(indices=True)
selector2 = SelectKBest(chi2, k=25)
X_new2 =selector2.fit_transform(Weighted_X2, Y_train2)
idxs_selected2 = selector2.get_support(indices=True)
selector3 = SelectKBest(chi2, k=25)
X_new3 =selector3.fit_transform(Weighted_X3, Y_train3)
idxs_selected3 = selector3.get_support(indices=True)
selector4 = SelectKBest(chi2, k=25)
X_new4 =selector4.fit_transform(Weighted_X4, Y_train4)
idxs_selected4 = selector4.get_support(indices=True)
selector5 = SelectKBest(chi2, k=25)
X_new5 =selector5.fit_transform(Weighted_X5, Y_train5)
idxs_selected5 = selector5.get_support(indices=True)

## Reading Test Data from unseen Data (Guaranteed_)

In [6]:
data_test = pd.read_csv("test.csv")
df_test = pd.DataFrame(data_test) # Converting data to Panda DataFrame
#df_test = df_test.sample(20)
#df_test.head() #gives statistics about the columns of the dataframe

In [7]:

X_test = df_test
Weighted_XTest = X_test[["ilp32",'ilp256','ilp2048','ilp65536','memops','ctrlops','intops','flops',
 'coldref fraction',
 'resuseDist2 fraction',
 'sfp',
 'dfp',
 'noconflict',
 'broadCast',
 'coalesced',
 'shMemBw',
 'gMemBw',
 'blocks',
 'pages',
 'lipRate',
 'mulf',
 'divf',
 'specialFn',
 'lbdiv16',

 'lbdiv32',
 'lbdiv64',
 'lbdiv128',
 'lbdiv256',
 'lbdiv512',
 'lbdiv1024']].multiply(df_test["instructionCount"], axis="index")


In [8]:
baggingClassifier1 = ensemble.BaggingClassifier(n_estimators=11,bootstrap_features=True,n_jobs=-1,random_state=0)
baggingClassifier1.fit(X_new1,Y_train1)
baggingClassifier2 = ensemble.BaggingClassifier(n_estimators=11,bootstrap_features=True,n_jobs=-1,random_state=0)
baggingClassifier2.fit(X_new2,Y_train2)
baggingClassifier3 = ensemble.BaggingClassifier(n_estimators=11,bootstrap_features=True,n_jobs=-1,random_state=0)
baggingClassifier3.fit(X_new3,Y_train3)
baggingClassifier4 = ensemble.BaggingClassifier(n_estimators=11,bootstrap_features=True,n_jobs=-1,random_state=0)
baggingClassifier4.fit(X_new4,Y_train4)
baggingClassifier5 = ensemble.BaggingClassifier(n_estimators=11,bootstrap_features=True,n_jobs=-1,random_state=0)
baggingClassifier5.fit(X_new5,Y_train5)

BaggingClassifier(base_estimator=None, bootstrap=True,
         bootstrap_features=True, max_features=1.0, max_samples=1.0,
         n_estimators=11, n_jobs=-1, oob_score=False, random_state=0,
         verbose=0, warm_start=False)

In [9]:
scores1 = cross_val_score(baggingClassifier1, X_new1, Y_train1)
scores2 = cross_val_score(baggingClassifier2, X_new2, Y_train2)
scores3 = cross_val_score(baggingClassifier3, X_new3, Y_train3)
scores4 = cross_val_score(baggingClassifier4, X_new4, Y_train4)
scores5 = cross_val_score(baggingClassifier5, X_new5, Y_train5)

avg = (scores1 + scores2 +scores3 + scores4 + scores5)/5
print avg

[0.83571429 0.68571429 0.71428571]


In [10]:
prediction1 = baggingClassifier1.predict(Weighted_XTest[Weighted_XTest.columns[idxs_selected1]])
print (prediction1)
prediction2 = baggingClassifier2.predict(Weighted_XTest[Weighted_XTest.columns[idxs_selected2]])
print (prediction2)
prediction3 = baggingClassifier3.predict(Weighted_XTest[Weighted_XTest.columns[idxs_selected3]])
print (prediction3)
prediction4 = baggingClassifier4.predict(Weighted_XTest[Weighted_XTest.columns[idxs_selected4]])
print (prediction4)
prediction5 = baggingClassifier5.predict(Weighted_XTest[Weighted_XTest.columns[idxs_selected5]])
print (prediction5)
total = prediction1+prediction2+prediction3+prediction4+prediction5
print (total)
totalNew = []
for value in total:
    if value > 2:
        totalNew.append('Y')
    else:
        totalNew.append('N')
print (np.array(totalNew))
print (np.array(X_test['Class']))

[0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 1 1]
[0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 0 1 1]
[0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1]
[1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0]
[2 2 2 4 3 3 2 3 2 2 2 1 1 2 2 2 2 2 1 1 5 5 5 4 4 4 3 4 4]
['N' 'N' 'N' 'Y' 'Y' 'Y' 'N' 'Y' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N'
 'N' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y']
['N' 'N' 'N' 'N' 'Y' 'Y' 'Y' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N'
 'N' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y']


In [12]:
accuracy_score(np.array(X_test['Class']),np.array(totalNew))

0.896551724137931

## Random Forest Classifier

In [13]:
randomForest1 = RandomForestClassifier(n_estimators=11,n_jobs=-1,random_state=0)
randomForest2 = RandomForestClassifier(n_estimators=11,n_jobs=-1,random_state=0)
randomForest3 = RandomForestClassifier(n_estimators=11,n_jobs=-1,random_state=0)
randomForest4 = RandomForestClassifier(n_estimators=11,n_jobs=-1,random_state=0)
randomForest5 = RandomForestClassifier(n_estimators=11,n_jobs=-1,random_state=0)
randomForest1.fit(X_new1,Y_train1)
randomForest2.fit(X_new2,Y_train2)
randomForest3.fit(X_new3,Y_train3)
randomForest4.fit(X_new4,Y_train4)
randomForest5.fit(X_new5,Y_train5)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=11, n_jobs=-1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [14]:
scores1 = cross_val_score(randomForest1, X_new1, Y_train1)
scores2 = cross_val_score(randomForest2, X_new2, Y_train2)
scores3 = cross_val_score(randomForest3, X_new3, Y_train3)
scores4 = cross_val_score(randomForest4, X_new4, Y_train4)
scores5 = cross_val_score(randomForest5, X_new5, Y_train5)

avg = (scores1 + scores2 +scores3 + scores4 + scores5)/5

print avg

[0.83571429 0.65714286 0.57142857]


In [18]:
prediction1 = randomForest1.predict(Weighted_XTest[Weighted_XTest.columns[idxs_selected1]])
print (prediction1)
prediction2 = randomForest2.predict(Weighted_XTest[Weighted_XTest.columns[idxs_selected2]])
print (prediction2)
prediction3 = randomForest3.predict(Weighted_XTest[Weighted_XTest.columns[idxs_selected3]])
print (prediction3)
prediction4 = randomForest4.predict(Weighted_XTest[Weighted_XTest.columns[idxs_selected4]])
print (prediction4)
prediction5 = randomForest5.predict(Weighted_XTest[Weighted_XTest.columns[idxs_selected5]])
print (prediction5)
total = prediction1+prediction2+prediction3+prediction4+prediction5
print (total)
totalNew = []
for value in total:
    if value > 2:
        totalNew.append('Y')
    else:
        totalNew.append('N')
print (np.array(totalNew))
print (np.array(X_test['Class']))


[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1]
[0 0 0 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[0 0 0 1 0 0 0 1 1 1 1 0 0 0 0 0 1 1 0 0 1 1 1 1 1 1 1 1 1]
[0 0 0 1 1 1 0 1 1 1 1 0 0 0 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1]
[0 0 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0]
[1 1 2 5 4 4 2 3 3 3 3 1 2 3 3 3 4 5 2 3 5 5 5 5 5 5 4 5 4]
['N' 'N' 'N' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'N' 'N' 'Y' 'Y' 'Y' 'Y' 'Y'
 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y']
['N' 'N' 'N' 'N' 'Y' 'Y' 'Y' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N'
 'N' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y']


In [19]:
accuracy_score(np.array(X_test['Class']),np.array(totalNew))

0.5862068965517241

## GaussianProcessClassifier 

In [20]:
gp_opt1 = GaussianProcessClassifier(kernel=1.0 * RBF(length_scale=0.5))
gp_opt2 = GaussianProcessClassifier(kernel=1.0 * RBF(length_scale=0.5))
gp_opt3 = GaussianProcessClassifier(kernel=1.0 * RBF(length_scale=0.5))
gp_opt4 = GaussianProcessClassifier(kernel=1.0 * RBF(length_scale=0.5))
gp_opt5 = GaussianProcessClassifier(kernel=1.0 * RBF(length_scale=0.5))
gp_opt1.fit(X_new1,Y_train1)
gp_opt2.fit(X_new2,Y_train2)
gp_opt3.fit(X_new3,Y_train3)
gp_opt4.fit(X_new4,Y_train4)
gp_opt5.fit(X_new5,Y_train5)

GaussianProcessClassifier(copy_X_train=True,
             kernel=1**2 * RBF(length_scale=0.5), max_iter_predict=100,
             multi_class='one_vs_rest', n_jobs=1, n_restarts_optimizer=0,
             optimizer='fmin_l_bfgs_b', random_state=None,
             warm_start=False)

In [21]:
scores1 = cross_val_score(gp_opt1, X_new1, Y_train1)
scores2 = cross_val_score(gp_opt2, X_new2, Y_train2)
scores3 = cross_val_score(gp_opt3, X_new3, Y_train3)
scores4 = cross_val_score(gp_opt4, X_new4, Y_train4)
scores5 = cross_val_score(gp_opt5, X_new5, Y_train5)

avg = (scores1 + scores2 +scores3 + scores4 + scores5)/5
print avg

[0.33214286 0.31428571 0.28571429]


In [22]:
prediction1 = gp_opt1.predict(Weighted_XTest[Weighted_XTest.columns[idxs_selected1]])
print (prediction1)
prediction2 = gp_opt2.predict(Weighted_XTest[Weighted_XTest.columns[idxs_selected2]])
print (prediction2)
prediction3 = gp_opt3.predict(Weighted_XTest[Weighted_XTest.columns[idxs_selected3]])
print (prediction3)
prediction4 = gp_opt4.predict(Weighted_XTest[Weighted_XTest.columns[idxs_selected4]])
print (prediction4)
prediction5 = gp_opt5.predict(Weighted_XTest[Weighted_XTest.columns[idxs_selected5]])
print (prediction5)
total = prediction1+prediction2+prediction3+prediction4+prediction5
print (total)
totalNew = []
for value in total:
    if value > 1:
        totalNew.append('Y')
    else:
        totalNew.append('N')
print (np.array(totalNew))
print (np.array(X_test['Class']))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1]
['N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N'
 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N']
['N' 'N' 'N' 'N' 'Y' 'Y' 'Y' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N'
 'N' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y']


In [23]:
accuracy_score(np.array(X_test['Class']),np.array(totalNew))

0.5862068965517241

## SVM Classifier

In [24]:
model1 = svm.SVC(kernel='rbf', gamma=1)
model2 = svm.SVC(kernel='rbf', gamma=1)
model3 = svm.SVC(kernel='rbf', gamma=1)
model4 = svm.SVC(kernel='rbf', gamma=1)
model5 = svm.SVC(kernel='rbf', gamma=1)
model1.fit(X_new1,Y_train1)
model2.fit(X_new2,Y_train2)
model3.fit(X_new3,Y_train3)
model4.fit(X_new4,Y_train4)
model5.fit(X_new5,Y_train5)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=1, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [25]:
scores1 = cross_val_score(model1, X_new1, Y_train1)
scores2 = cross_val_score(model2, X_new2, Y_train2)
scores3 = cross_val_score(model3, X_new3, Y_train3)
scores4 = cross_val_score(model4, X_new4, Y_train4)
scores5 = cross_val_score(model5, X_new5, Y_train5)

avg = (scores1 + scores2 +scores3 + scores4 + scores5)/5
print avg

[0.69642857 0.71428571 0.71428571]


In [26]:
prediction1 = model1.predict(Weighted_XTest[Weighted_XTest.columns[idxs_selected1]])
print (prediction1)
prediction2 = model2.predict(Weighted_XTest[Weighted_XTest.columns[idxs_selected2]])
print (prediction2)
prediction3 = model3.predict(Weighted_XTest[Weighted_XTest.columns[idxs_selected3]])
print (prediction3)
prediction4 = model4.predict(Weighted_XTest[Weighted_XTest.columns[idxs_selected4]])
print (prediction4)
prediction5 = model5.predict(Weighted_XTest[Weighted_XTest.columns[idxs_selected5]])
print (prediction5)
print (np.array(X_test['Class']))

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
['N' 'N' 'N' 'N' 'Y' 'Y' 'Y' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N'
 'N' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y']


In [27]:
accuracy_score(np.array(X_test['Class']),np.array(totalNew))

0.5862068965517241